In [17]:
import numpy as np

# Randomly generate a general 3x3 square matrix A
np.random.seed(42)

# =====================================================================
# === SECTION 3.12: Eigenvalues and Eigenvectors                    ===
# =====================================================================

print("--- Verifying Section 3.12: General Square Matrices ---")

A = np.random.randn(3, 3)

# Compute eigenvalues and eigenvectors
# Note: Each column of the 'eigenvectors' matrix corresponds to an eigenvector
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:\n", A)
print("\nEigenvalues:\n", eigenvalues)

# Verify the first eigenvalue/eigenvector pair: Ax = lambda * x
lambda_0 = eigenvalues[0]
x_0 = eigenvectors[:, 0]

Ax = A @ x_0
lambda_x = lambda_0 * x_0

print("\nVerifying Ax = lambda * x:")
print("Ax:\n", Ax)
print("lambda * x:\n", lambda_x)
print("Are they equal (allowing for tiny numerical precision errors)?", np.allclose(Ax, lambda_x))

# Verify that eigenvectors are normalized (norm = 1)
for i in range(3):
    norm = np.linalg.norm(eigenvectors[:, i])
    print(f"Norm of eigenvector {i}: {norm:.4f}")

--- Verifying Section 3.12: General Square Matrices ---
Matrix A:
 [[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]

Eigenvalues:
 [ 1.22795686+0.j         -0.71743524+0.61245434j -0.71743524-0.61245434j]

Verifying Ax = lambda * x:
Ax:
 [0.66591538+0.j 0.55431799+0.j 0.87015305+0.j]
lambda * x:
 [0.66591538+0.j 0.55431799+0.j 0.87015305+0.j]
Are they equal (allowing for tiny numerical precision errors)? True
Norm of eigenvector 0: 1.0000
Norm of eigenvector 1: 1.0000
Norm of eigenvector 2: 1.0000


In [9]:
# 1. Trace equals the sum of eigenvalues
trace_A = np.trace(A)
sum_lambdas = np.sum(eigenvalues)
print(f"Trace of A: {trace_A:.6f}, Sum of eigenvalues: {sum_lambdas.real:.6f}")
print("Trace property verified:", np.isclose(trace_A, sum_lambdas))

Trace of A: -0.206914, Sum of eigenvalues: -0.206914
Trace property verified: True


In [11]:
# 2. Determinant equals the product of eigenvalues
det_A = np.linalg.det(A)
prod_lambdas = np.prod(eigenvalues)
print(f"Determinant of A: {det_A:.6f}, Product of eigenvalues: {prod_lambdas.real:.6f}")
print("Determinant property verified:", np.isclose(det_A, prod_lambdas))

Determinant of A: 1.092653, Product of eigenvalues: 1.092653
Determinant property verified: True


In [13]:
# 3. Rank of A equals the number of non-zero eigenvalues (for diagonalizable matrices)
# Construct a rank-deficient matrix (Rank = 1)
A_deficient = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]], dtype=float)
eig_def = np.linalg.eigvals(A_deficient)
rank_actual = np.linalg.matrix_rank(A_deficient)
non_zero_eigs = np.sum(np.abs(eig_def) > 1e-9)
print(f"Actual rank of deficient matrix: {rank_actual}, Number of non-zero eigenvalues: {non_zero_eigs}")

Actual rank of deficient matrix: 1, Number of non-zero eigenvalues: 1


In [15]:
# 4. Eigenvalues of the inverse matrix are the reciprocals of the original eigenvalues: A^-1 * x = (1/λ) * x
A_inv = np.linalg.inv(A)
eig_inv = np.linalg.eigvals(A_inv)
print("Eigenvalues of A^-1:     ", sorted(eig_inv, key=abs))
print("1 / (Eigenvalues of A):  ", sorted(1 / eigenvalues, key=abs))

Eigenvalues of A^-1:      [np.complex128(0.8143608534329512+0j), np.complex128(-0.8062758343943134+0.6882950716277916j), np.complex128(-0.8062758343943134-0.6882950716277916j)]
1 / (Eigenvalues of A):   [np.complex128(0.8143608534329522+0j), np.complex128(-0.8062758343943126-0.6882950716277918j), np.complex128(-0.8062758343943126+0.6882950716277918j)]


In [16]:
# 5. Eigenvalues of a diagonal matrix are simply its diagonal entries
D = np.diag([1.5, -2.0, 3.5])
print("Eigenvalues of diagonal matrix D:", np.linalg.eigvals(D))

Eigenvalues of diagonal matrix D: [ 1.5 -2.   3.5]


In [25]:
# =====================================================================
# === SECTION 3.13: Eigenvalues and Eigenvectors of Symmetric Matrices ===
# =====================================================================

print("--- Verifying Section 3.13: Real Symmetric Matrices ---")

# Construct a real symmetric matrix S (S = B + B^T)
B = np.random.randn(3, 3)
S = B + B.T

# Use eigh, which is optimized for symmetric matrices
lambdas, U = np.linalg.eigh(S)

# --- 3.13 [Property 1 & 2]: Real eigenvalues & Orthonormal U ---
print("Symmetric Matrix S:\n", S)
print("\n[Property 1] Eigenvalues (All real!):", lambdas)
print("\n[Property 2] Verify U is orthonormal (U^T @ U = I):")
print(np.round(U.T @ U, 6))

# --- 3.13 [Equation 6]: Diagonalization / Spectral Decomposition (S = U @ Lambda @ U^T) ---
Lambda = np.diag(lambdas)
S_reconstructed = U @ Lambda @ U.T
print("\n[Eq 6] Reconstructed S from U @ Lambda @ U^T:\n", S_reconstructed)
print("Diagonalization successful:", np.allclose(S, S_reconstructed))

--- Verifying Section 3.13: Real Symmetric Matrices ---
Symmetric Matrix S:
 [[-0.07165208  2.38654616 -2.52798433]
 [ 2.38654616  0.17409414 -2.28657627]
 [-2.52798433 -2.28657627 -0.43934378]]

[Property 1] Eigenvalues (All real!): [-2.79314107 -2.23884943  4.69508878]

[Property 2] Verify U is orthonormal (U^T @ U = I):
[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]

[Eq 6] Reconstructed S from U @ Lambda @ U^T:
 [[-0.07165208  2.38654616 -2.52798433]
 [ 2.38654616  0.17409414 -2.28657627]
 [-2.52798433 -2.28657627 -0.43934378]]
Diagonalization successful: True


In [26]:
# --- 3.13 [Background]: Representing vector w.r.t. another basis (x_hat = U^T @ x) ---
x = np.random.randn(3)
x_hat = U.T @ x
print("\n[Background] Original x:", x)
print("[Background] x_hat (in U basis):", x_hat)
print("[Background] Recover x via (U @ x_hat) matches?", np.allclose(x, U @ x_hat))


[Background] Original x: [ 0.35711257  1.47789404 -0.51827022]
[Background] x_hat (in U basis): [-0.07093409 -0.8377401   1.36874545]
[Background] Recover x via (U @ x_hat) matches? True


In [28]:
# --- 3.13 [Diagonalizing Matrix-Vector Multiplication]: U^T @ S @ x = Lambda @ x_hat ---
z = S @ x
z_hat = U.T @ z
Lambda_x_hat = Lambda @ x_hat
print("\n[Matrix-Vector Mult] z_hat via definition:", z_hat)
print("[Matrix-Vector Mult] z_hat via Lambda scaling:", Lambda_x_hat)
print("Are they identical?", np.allclose(z_hat, Lambda_x_hat))

# --- 3.13 [Equation 7]: Multiplying a matrix multiple times (S^3 @ x) ---
q = S @ S @ S @ x
q_hat = U.T @ q
Lambda3_x_hat = np.diag(lambdas ** 3) @ x_hat
print("\n[Eq 7] S^3 product in new basis:", q_hat)
print("[Eq 7] Lambda^3 scaling result:", Lambda3_x_hat)
print("Are they identical?", np.allclose(q_hat, Lambda3_x_hat))


[Matrix-Vector Mult] z_hat via definition: [0.19812892 1.87557394 6.42638138]
[Matrix-Vector Mult] z_hat via Lambda scaling: [0.19812892 1.87557394 6.42638138]
Are they identical? True

[Eq 7] S^3 product in new basis: [  1.54572995   9.40121456 141.66224288]
[Eq 7] Lambda^3 scaling result: [  1.54572995   9.40121456 141.66224288]
Are they identical? True


In [ ]:
# --- 3.13 [Equation 8]: Diagonalizing Quadratic Form (x^T @ S @ x) ---
quad_form_orig = x.T @ S @ x
quad_form_simplified = np.sum(lambdas * (x_hat ** 2))
print(f"\n[Eq 8] Quadratic form (Original space): {quad_form_orig:.6f}")
print(f"[Eq 8] Quadratic form (Simplified sum):  {quad_form_simplified:.6f}")
print("Are they equal?", np.isclose(quad_form_orig, quad_form_simplified))

In [31]:
# --- 3.13 [Definiteness]: Definiteness depends entirely on the sign of eigenvalues ---
# S_pos = S @ S^T is guaranteed to be Positive Definite (all lambdas > 0)
S_pos = S @ S.T
lambdas_pos = np.linalg.eigvalsh(S_pos)
print("\n[Definiteness] Eigenvalues of S_pos (All > 0):", lambdas_pos)
print("[Definiteness] Is x^T * S_pos * x > 0 for non-zero x?", (x.T @ S_pos @ x) > 0)


[Definiteness] Eigenvalues of S_pos (All > 0): [ 5.01244677  7.80163702 22.04385865]
[Definiteness] Is x^T * S_pos * x > 0 for non-zero x? True


In [37]:
# --- 3.13 [Equation 9 & 10]: Maximizing Quadratic Form (Rayleigh Quotient) ---
idx_max = np.argmax(lambdas)
max_lambda = lambdas[idx_max]
best_x = U[:, idx_max]  # Eigenvector corresponding to lambda_max
print(f"\n[Eq 9-10] Theoretical Max Value (lambda_max): {max_lambda:.6f}")
print(f"[Eq 9-10] Quadratic form using optimal eigenvector u1: {best_x.T @ S @ best_x:.6f}")

# Empirical check using 10,000 random unit vectors
max_sampled = -float('inf')
for _ in range(10000):
    rand_x = np.random.randn(3)
    rand_x /= np.linalg.norm(rand_x)
    val = rand_x.T @ S @ rand_x
    if val > max_sampled:
      max_sampled = val
print(f"[Eq 9-10] Max value found via 10,000 random samples: {max_sampled:.6f}")
print("Optimization theorem holds true?", max_lambda >= max_sampled)


[Eq 9-10] Theoretical Max Value (lambda_max): 4.695089
[Eq 9-10] Quadratic form using optimal eigenvector u1: 4.695089
[Eq 9-10] Max value found via 10,000 random samples: 4.695002
Optimization theorem holds true? True
