In [5]:
import numpy as np

# =====================================================================
# SECTION 3.1: IDENTITY MATRIX AND DIAGONAL MATRICES
# =====================================================================

# 1. Create a 3x3 identity matrix I
I = np.eye(3)
print("Identity Matrix I:\n", I)

# 2. Verify AI = A = IA
A = np.array([[1, 2, 3], 
              [4, 5, 6]])  # 2x3 matrix
I_3 = np.eye(3)  # 3x3 identity matrix
I_2 = np.eye(2)  # 2x2 identity matrix

AI = A @ I_3
IA = I_2 @ A
print("\nA multiplied by I_3:\n", AI)
print("I_2 multiplied by A:\n", IA)
print("Do both equal the original matrix A?", np.allclose(AI, A), np.allclose(A, IA))

# 3. Create a diagonal matrix D = diag(1, 4, 7)
v = [1, 4, 7]
D = np.diag(v)
print("\nDiagonal Matrix D:\n", D)

Identity Matrix I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A multiplied by I_3:
 [[1. 2. 3.]
 [4. 5. 6.]]
I_2 multiplied by A:
 [[1. 2. 3.]
 [4. 5. 6.]]
Do both equal the original matrix A? True True

Diagonal Matrix D:
 [[1 0 0]
 [0 4 0]
 [0 0 7]]


In [9]:
# =====================================================================
# SECTION 3.2: THE TRANSPOSE
# =====================================================================

A = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])
B = np.array([[7, 8], 
              [9, 10]])
# 1. Verify (A^T)^T = A
print("Do (A^T)^T equal matrix A?", np.allclose(A.T.T, A))

# 2. Verify (AB)^T = B^T * A^T
# Note: Matrix multiplication in Python uses the @ operator or np.dot()
left_side = (A @ B).T
right_side = B.T @ A.T
print("Do (AB)^T equal B^T * A^T?", np.allclose(left_side, right_side))

# 3. Verify (A + C)^T = A^T + C^T
C = np.array([[1, 1], [1, 1], [1, 1]])
left_side = (A + C).T
right_side = A.T + C.T
print("Do (A + C)^T  equal  A^T + C^T?", np.allclose(left_side, right_side))

Do (A^T)^T equal matrix A? True
Do (AB)^T equal B^T * A^T? True
Do (A + C)^T  equal  A^T + C^T? True


In [13]:
# =====================================================================
# SECTION 3.3: SYMMETRIC AND ANTI-SYMMETRIC MATRICES
# =====================================================================
# Create a random 3x3 square matrix
A = np.array([[1, 3, 5],
              [7, 9, 2],
              [4, 6, 8]])

# Decompose into symmetric and anti-symmetric parts
A_sym = 0.5 * (A + A.T)
A_anti = 0.5 * (A - A.T)
print("Symmetric matrix part A_sym:\n", A_sym)
print("Anti-symmetric matrix part A_anti:\n", A_anti)

# Verification 1: A_sym is indeed symmetric (A_sym == A_sym.T)
print("\nIs A_sym a symmetric matrix?", np.allclose(A_sym, A_sym.T))

# Verification 2: A_anti is indeed anti-symmetric (A_anti == -A_anti.T)
print("Is A_anti an anti-symmetric matrix?", np.allclose(A_anti, -A_anti.T))

# Verification 3: Adding them together restores the original matrix A
print("Does the sum of both equal A?", np.allclose(A_sym + A_anti, A))

Symmetric matrix part A_sym:
 [[1.  5.  4.5]
 [5.  9.  4. ]
 [4.5 4.  8. ]]
Anti-symmetric matrix part A_anti:
 [[ 0.  -2.   0.5]
 [ 2.   0.  -2. ]
 [-0.5  2.   0. ]]

Is A_sym a symmetric matrix? True
Is A_anti an anti-symmetric matrix? True
Does the sum of both equal A? True


In [16]:
# =====================================================================
# SECTION 3.4: THE TRACE
# =====================================================================
A = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])  # 3x2 matrix
B = np.array([[7, 8, 9], 
              [10, 11, 12]])  # 2x3 matrix
AB = A @ B # 3x3 matrix
BA = B @ A # 2x2 matrix
trace_AB = np.trace(AB)
trace_BA = np.trace(BA)

print("Main diagonal elements of AB:", np.diag(AB), "-> Trace:", trace_AB)
print("Main diagonal elements of BA:", np.diag(BA), "-> Trace:", trace_BA)
print("Does tr(AB) equal tr(BA)?", np.isclose(trace_AB, trace_BA))

Main diagonal elements of AB: [ 27  68 117] -> Trace: 212
Main diagonal elements of BA: [ 76 136] -> Trace: 212
Does tr(AB) equal tr(BA)? True


In [25]:
# =====================================================================
# SECTION 3.5: NORMS (VECTORS AND MATRICES)
# =====================================================================
x = np.array([3, -4, 12])

# 1. Vector l2 norm (default norm in NumPy)
l2_norm = np.linalg.norm(x) # Equivalent to sqrt(3^2 + (-4)^2 + 12^2) = 13
print("l2 norm (Euclidean distance):", l2_norm)
print("Verify ||x||_2^2 == x^T * x:",np.allclose(l2_norm **2, x.T @ x))

# 2. Vector l1 norm
l1_norm = np.linalg.norm(x, ord=1) # Equivalent to |3| + |-4| + |12| = 19
print("l1 norm (Euclidean distance):", l1_norm)

# 3. Vector l_infinity norm
linf_norm = np.linalg.norm(x, ord=np.inf) # Equivalent to max(|3|, |-4|, |12|) = 12
print("l infinity norm (Euclidean distance):", linf_norm)

# 4. Matrix Frobenius norm
A = np.array([[1, 2], 
              [3, 4]])
f_norm = np.linalg.norm(A, ord='fro')
print("\nFrobenius norm of matrix A:", f_norm)

# Verify ||A||_F = sqrt(tr(A^T * A))
f_norm_verify = np.sqrt(np.trace(A.T @ A))
print("Verified result via tr(A^T A):", f_norm_verify)

l2 norm (Euclidean distance): 13.0
Verify ||x||_2^2 == x^T * x: True
l1 norm (Euclidean distance): 19.0
l infinity norm (Euclidean distance): 12.0

Frobenius norm of matrix A: 5.477225575051661
Verified result via tr(A^T A): 5.477225575051661
