In [2]:
import numpy as np

# =====================================================================
# Matrix A1: Healthy data, all three columns are completely independent
# =====================================================================
A1 = np.array([[1.0, 2.0, 3.0],
               [4.0, 5.0, 6.0],
               [7.0, 8.0, 10.0]]) # Note that the bottom-right element is 10

# =====================================================================
# Matrix A2: Redundant data, the third column is exactly twice the first!
# =====================================================================
A2 = np.array([[1.0, 2.0, 2.0],
               [4.0, 5.0, 8.0],
               [7.0, 8.0, 14.0]]) # Column 3 = Column 1 * 2


# Measure their Matrix Ranks
rank_A1 = np.linalg.matrix_rank(A1)
rank_A2 = np.linalg.matrix_rank(A2)

print(f"Matrix A1 (No Redundancy) shape is 3x3, calculated rank: {rank_A1} -> [Full Rank!]")
print(f"Matrix A2 (Contains Redundancy) shape is 3x3, calculated rank: {rank_A2} -> [Not Full Rank, Info Deflated!]\n")

Matrix A1 (No Redundancy) shape is 3x3, calculated rank: 3 -> [Full Rank!]
Matrix A2 (Contains Redundancy) shape is 3x3, calculated rank: 2 -> [Not Full Rank, Info Deflated!]



In [3]:
# =====================================================================
# Attempting to invert A^T @ A for both matrices
# =====================================================================
try:
    inv_A1 = np.linalg.inv(A1.T @ A1)
    print("Success: A1.T @ A1 inverted successfully! The formula is safe to run.")
except np.linalg.LinAlgError:
    print("Failure: A1.T @ A1 inversion failed!")

try:
    inv_AA = np.linalg.inv(A2.T @ A2)
    print("Success: A2.T @ A2 inverted successfully! The formula is safe to run.")
except np.linalg.LinAlgError:
    print("Failure: A2.T @ A2 raised an Error: Singular Matrix, inversion failed because information deflated!")

Success: A1.T @ A1 inverted successfully! The formula is safe to run.
Failure: A2.T @ A2 raised an Error: Singular Matrix, inversion failed because information deflated!


In [7]:
# =====================================================================
# SECTION 3.7: THE INVERSE OF A SQUARE MATRIX
# =====================================================================

# Create a full-rank 2x2 square matrix (non-singular matrix)
B = np.array([[1, 2], 
              [3, 4]])
# Calculate the inverse matrix B^-1
B_inv = np.linalg.inv(B)
print(f"\nMatrix B:\n{B}")
print(f"Inverse of B (B^-1):\n{B_inv}")

# 1. Verify B^-1 @ B = I (Identity Matrix)
print("\nVerify B_inv @ B:")
print(B_inv @ B)

print("Is B_inv @ B close to the Identity Matrix?", np.allclose(B_inv @ B, np.eye(2)))

# 3. Solve the linear system Bx = d -> x = B^-1 * d
d = np.array([5, 11])
# Method 1: Multiply directly by the inverse matrix (demonstrating the mathematical principle)
x_method1 = B_inv @ d
# Method 2: Use NumPy's highly efficient and recommended solver np.linalg.solve()
x_method2 = np.linalg.solve(B, d)
print(f"\nSolution x (Method 1): {x_method1}")
print(f"Solution x (Method 2): {x_method2}")


Matrix B:
[[1 2]
 [3 4]]
Inverse of B (B^-1):
[[-2.   1. ]
 [ 1.5 -0.5]]

Verify B_inv @ B:
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
Is B_inv @ B close to the Identity Matrix? True

Solution x (Method 1): [1. 2.]
Solution x (Method 2): [1. 2.]


In [13]:
# =====================================================================
# SECTION 3.8: ORTHOGONAL MATRICES
# =====================================================================
# Create a standard 2D rotation matrix (rotated by 30 degrees), which is a standard orthogonal matrix
theta = np.radians(30)
U = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])
print(f"\nOrthogonal Matrix U (30 deg rotation):\n{U}")

# 1. Verify U^T @ U = I (Core property of orthogonal matrices: inverse equals transpose)
print(f"U^T @ U equals to I", np.allclose(U.T @ U, np.eye(2)))
print(f"U @ U^T equals to I", np.allclose(U @ U.T, np.eye(2)))

# 2. Verify "length-preserving" property: An orthogonal matrix transformation does not change the Euclidean length (l2 norm) of a vector
v = np.array([3, 4])  # Length is sqrt(3^2 + 4^2) = 5
norm_v = np.linalg.norm(v)
U_v = U @ v
norm_U_v = np.linalg.norm(U_v)
print(f"\nOriginal vector v: {v}, Length: {norm_v}")
print(f"Transformed vector U@v: {U_v}, Length: {norm_U_v}")
print("Are the lengths identical?", np.isclose(norm_v, norm_U_v))


Orthogonal Matrix U (30 deg rotation):
[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]
U^T @ U equals to I True
U @ U^T equals to I True

Original vector v: [3 4], Length: 5.0
Transformed vector U@v: [0.59807621 4.96410162], Length: 5.0
Are the lengths identical? True


In [14]:
# =====================================================================
# SECTION 3.9: MATRIX CALCULUS / EXTRA PROPERTIES
# =====================================================================
# Note: Although section 3.9 was not explicitly provided in the text, it typically covers 
# Determinants or Eigenvalues right after. The most common NumPy implementations are included below:

# 1. Calculate the determinant det(B) —— A matrix is invertible if and only if its determinant is not 0
det_B = np.linalg.det(B)
print(f"\nDeterminant of B: {det_B}")


Determinant of B: -2.0000000000000004


In [18]:
# =====================================================================
# SECTION 3.9: RANGE AND NULLSPACE OF A MATRIX
# =====================================================================

# 1. Verify the projection formula: Proj(y; A) = A @ inv(A.T @ A) @ A.T @ y
# We assume A is a full-rank 3x2 matrix (n < m), and y is a 3D column vector.
A = np.array([[1, 2],
              [3, 4],
              [5, 8]])  # Shape: (3, 2)
y = np.array([1, 5, 3])  # Shape: (3,)
# Calculate the projection vector v directly using the textbook formula:
# A(A^T A)^-1 A^T y
v_formula = A @ np.linalg.inv(A.T @ A) @ A.T @ y
print("--- 3.9 Projection and Geometric Verification ---")
print(f"Formula-based projection v:\n{v_formula}")

# 2. Verify the Nullspace
# NumPy does not have a built-in function named 'nullspace' (though scipy.linalg does).
# In pure NumPy, we can find the nullspace basis accurately using Singular Value Decomposition (SVD).
# To demonstrate, we create a matrix C where rows are linearly dependent.
C = np.array([[1, 2, 3],
              [2, 4, 6],  # Row 1 is exactly 2 times Row 0
              [4, 5, 6]])
# Use SVD to find the basis of the nullspace
U_mat, S_mat, Vt_mat = np.linalg.svd(C)
print(f"\n S {U_mat} \n v {S_mat} \n d {Vt_mat}")
# Find the V vectors that correspond to singular values close to 0
null_mask = S_mat < 1e-10
null_space = Vt_mat[null_mask].T
print(f"\nMatrix C:\n{C}")
print(f"Nullspace basis of C:\n{null_space}")

--- 3.9 Projection and Geometric Verification ---
Formula-based projection v:
[-0.33333333  4.33333333  3.66666667]

 S [[-3.08406294e-01 -3.23860398e-01 -8.94427191e-01]
 [-6.16812589e-01 -6.47720797e-01  4.47213595e-01]
 [-7.24173866e-01  6.89617439e-01  2.60909417e-16]] 
 v [1.20473949e+01 1.36391949e+00 7.21618321e-16] 
 d [[-0.36843874 -0.55654624 -0.74465374]
 [ 0.83521628  0.15358913 -0.52803802]
 [-0.40824829  0.81649658 -0.40824829]]

Matrix C:
[[1 2 3]
 [2 4 6]
 [4 5 6]]
Nullspace basis of C:
[[-0.40824829]
 [ 0.81649658]
 [-0.40824829]]


In [29]:
# =====================================================================
# SECTION 3.10: THE DETERMINANT
# =====================================================================
print("\n--- 3.10 Determinant Properties Verification ---")

# 1. Verify the 2x2 matrix example from the textbook (Equation 4)
# A = [[1, 3], [3, 2]], theoretically det(A) = 1*2 - 3*3 = -7
A_2x2 = np.array([[1, 3],
                  [3, 2]], dtype=float)
det_A = np.linalg.det(A_2x2)
print(f"Determinant of the 2x2 matrix (should be -7): {det_A:.2f}")
print(f"The area of the transformed parallelogram is: {abs(det_A):.2f}")

# 2. Verify Property 1: |I| = 1
I = np.eye(3)
print(f"\nDeterminant of Identity Matrix I: {np.linalg.det(I)}")

# 3. Verify Property 2: Scaling a single row by t scales the determinant by t
t = 5.0
A_scaled_row = A_2x2.copy()
A_scaled_row[0, :] = A_scaled_row[0, :] * t
A_scaled_row_det = np.linalg.det(A_scaled_row)
print("Are they equal?", np.isclose(A_scaled_row_det, det_A * t))

# 4. Verify Property 3: Swapping two rows flips the sign of the determinant
A_swapped = A_2x2[[1, 0], :]
A_swapped_det = np.linalg.det(A_swapped) 
print("Are they equal?", np.isclose(A_swapped_det, -det_A))

# 5. Verify the derived property: |AB| = |A| * |B|
B_2x2 = np.array([[2, 0],
                  [1, 5]], dtype=float)
det_B = np.linalg.det(B_2x2)
det_AB = np.linalg.det(A_2x2 @ B_2x2)
print("Are they equal?", np.isclose(det_AB, det_A * det_B))

# 6. Verify the derived property: The determinant of a singular matrix is 0
# Matrix C from above is singular (not full rank), so its determinant should be 0
print(f"\nDeterminant of singular matrix C: {np.linalg.det(C)}")
print("Is it close to 0?", np.isclose(np.linalg.det(C), 0.0, atol=1e-10))


--- 3.10 Determinant Properties Verification ---
Determinant of the 2x2 matrix (should be -7): -7.00
The area of the transformed parallelogram is: 7.00

Determinant of Identity Matrix I: 1.0
Are they equal? True
Are they equal? True
Are they equal? True

Determinant of singular matrix C: 0.0
Is it close to 0? True
