In [15]:
import numpy as np

a = np.full((2, 2), 7)
print(a)

b = np.random.random((2, 2))
print(b)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2, shared memory
b = a[:2, 1: 3]
print(a)
print(b)

print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

row_r1 = a[1, :] # view second row as one dimensional array
row_r2 = a[1: 2, :] # view second row as two dimensional array
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[[7 7]
 [7 7]]
[[0.69412609 0.82390117]
 [0.32217284 0.51447078]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
b = a[[0, 1, 2], [0, 1, 0]]
print(b, b.shape)
# The above example of integer array indexing is equivalent to this:
c = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(c, c.shape)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5] (3,)
[1 4 5] (3,)


In [41]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([0, 2, 0, 1])
# Select one element from each row of a using the indices in b
c = a[np.arange(4), b] 
print(c)
c += 10
print(a)
a[np.arange(4), b]  += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [44]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx]) #construct an array with bool_idx value is true
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(x * y) #element wise multiplication
print(x.dot(y)) #matrix multiplication
print(np.dot(x, y)) #matrix multiplication
print(x @ y) #matrix multiplication

print(v * w) #element wise multiplication
print(v.dot(w)) #matrix multiplication
print(v @ w) #matrix multiplication

print(np.sum(x)) # sum of all
print(np.sum(x, axis=0)) # sum of each column
print(np.sum(x, axis=1)) # sum of in each row

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[ 99 120]
219
219
10
[4 6]
[3 7]


In [61]:
# broadcasting
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

for i in range(y.shape[0]):
    y[i, :] = x[i, :] + v

print(y)

vv = np.tile(v, (4, 1)) # Stack 4 copies of v on top of each other
print(x + vv)

#broadcasting
print(x + v)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [69]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

#compute outer product of v and w
y = np.reshape(v, (3,1)) * w # trigger broadcasting (3, 1) * (2,) -> (3, 2)
print(y)
print(np.outer(v, w))

# Add vector (v) to each row of a matrix (x)
x = np.array([[1,2,3], [4,5,6]]) # (2, 3)
print (x + v) # (2, 3) + (3,) -> (2, 3)

#add vector (w) to each column of a matrix (x)
print(x) # (2, 3)
print(x.T) # (3, 2)
print(x.T + w) #(3, 2) + (2,) -> (3, 2)
print((x.T + w).T) # (2, 3)
print(x + np.reshape(w, (2, 1))) #alternatively
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[ 5  9]
 [ 6 10]
 [ 7 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
from scipy.spatial.distance import pdist, squareform

x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

d = squareform(pdist(x, 'euclidean'))
print(d)



[[0 1]
 [1 0]
 [2 0]]
[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]


In [ ]:
import matplotlib.pyplot as plt
