In [4]:
import torch
# permutation of tensors
x = torch.rand((2, 3))
y = torch.einsum("ij -> ji", x) #transpose
print(x)
print(y)

tensor([[0.8864, 0.9033, 0.9365],
        [0.4653, 0.9380, 0.7516]])
tensor([[0.8864, 0.4653],
        [0.9033, 0.9380],
        [0.9365, 0.7516]])


In [8]:
# Summation
y = torch.einsum("ij ->", x)
print(y)

# Column sum
y = torch.einsum("ij -> j", x)
print(y)

# Row sum
y = torch.einsum("ij -> i", x)
print(y)

tensor(4.8810)
tensor([1.3517, 1.8413, 1.6881])
tensor([2.7262, 2.1548])


In [11]:
# matrix multiplication
x = torch.rand((2, 3))
v = torch.rand((1, 3))
# x @ v.T
y = torch.einsum("ij, kj -> ik", x, v)
print(y)
# x @ x.T
y = torch.einsum("ij, kj -> ik", x, x)
print(y)


tensor([[0.9709],
        [0.5080]])
tensor([[1.6266, 0.5554],
        [0.5554, 0.5767]])


In [19]:
# Dot product first row with first row of matrix
y = torch.einsum("i, i ->", x[0], x[0])
print(y)

# Dot product with matrix
x = torch.ones((2, 3))
y = torch.einsum("ij, ij ->", x, x * 2)
print(x)
print(y)

# Hadamard product (element wise multiplication)
y = torch.einsum("ij, ij -> ij", x, x * 2)
print(y)

tensor(3.)
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor(12.)
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [25]:
# outer product
a = torch.ones((3)) * 2
b = torch.ones((5)) * 3
y = torch.einsum("i, j -> ij", a, b)
print(y)

# batch matrix multiplication
a = torch.ones((3, 2, 5))
b = torch.ones((3, 5, 3))
y = torch.einsum("bij, bjk -> bik", a, b)
print(y)

tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])
tensor([[[5., 5., 5.],
         [5., 5., 5.]],

        [[5., 5., 5.],
         [5., 5., 5.]],

        [[5., 5., 5.],
         [5., 5., 5.]]])


In [27]:
# matrix diagonal
x = torch.rand((3, 3))
y = torch.einsum("ii -> i", x)
print(x)
print(y)

# matrix trace
y = torch.einsum("ii ->", x)
print(y)


tensor([[0.6577, 0.2728, 0.0986],
        [0.2706, 0.4406, 0.7383],
        [0.1691, 0.7843, 0.9257]])
tensor([0.6577, 0.4406, 0.9257])
tensor(2.0240)
