In [1]:
import numpy as np

# To ensure the matrix is symmetric positive-definite (as required in Section 4.5), 
# we generate a random matrix and construct a positive-definite matrix via B = A.T @ A.
np.random.seed(42)
seed_matrix = np.random.rand(3, 3)
A = seed_matrix.T @ seed_matrix
print(A)

[[0.50204599 0.49979317 0.40246347]
 [0.49979317 1.67846062 1.24092665]
 [0.40246347 1.24092665 0.92148868]]


In [4]:
# ==========================================
# 1. Verifying ∇|A| = |A| * A^{-T}
# ==========================================
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
grad_det_analytical = det_A * inv_A.T
h = 1e-6  # A tiny step size for numerical differentiation

# Numerical solution (Brute-force calculation using tiny changes in the determinant)
grad_det_numerical = np.zeros_like(A)
for i in range(A.shape[0]):
 for j in range(A.shape[1]):
     A_plus = A.copy()
     A_minus = A.copy()
     A_plus[i,j] += h
     A_minus[i, j] -= h
     grad_det_numerical[i, j] = (np.linalg.det(A_plus) - np.linalg.det(A_minus)) / (2 * h)

print("1. Determinant Gradient Verification:")
print("Analytical Gradient:\n", grad_det_analytical)
print("Numerical Gradient:\n", grad_det_numerical)
print("Are they extremely close?:", np.allclose(grad_det_analytical, grad_det_numerical, atol=1e-5))
print("-" * 50)

1. Determinant Gradient Verification:
Analytical Gradient:
 [[ 0.00678351  0.0388739  -0.05531243]
 [ 0.0388739   0.30065285 -0.42185375]
 [-0.05531243 -0.42185375  0.59287121]]
Numerical Gradient:
 [[ 0.00678351  0.0388739  -0.05531243]
 [ 0.0388739   0.30065285 -0.42185375]
 [-0.05531243 -0.42185375  0.59287121]]
Are they extremely close?: True
--------------------------------------------------


In [7]:
# ==========================================
# 2. Verifying ∇ log|A| = A^{-1}
# ==========================================
# Analytical solution
grad_logdet_analytical = inv_A  # The transpose is dropped due to symmetry

# Numerical solution (Brute-force calculation using tiny changes in the determinant)
grad_logdet_numerical = np.zeros_like(A)
for i in range(A.shape[0]):
 for j in range(A.shape[1]):
     A_plus = A.copy()
     A_minus = A.copy()
     A_plus[i,j] += h
     A_minus[i, j] -= h
     grad_logdet_numerical[i, j] = (np.log(np.linalg.det(A_plus)) - np.log(np.linalg.det(A_minus))) / (2 * h)

print("2. log|A| Gradient Verification:")
print("Analytical Gradient:\n", grad_logdet_analytical)
print("Numerical Gradient:\n", grad_logdet_numerical)
print("Are they extremely close?:", np.allclose(grad_logdet_analytical, grad_logdet_numerical, atol=1e-5))

2. log|A| Gradient Verification:
Analytical Gradient:
 [[  11.83210763   67.8056028   -96.47841878]
 [  67.8056028   524.41221378 -735.81627818]
 [ -96.47841878 -735.81627818 1034.11261632]]
Numerical Gradient:
 [[  11.8321076    67.80560284  -96.47841911]
 [  67.80560282  524.41226181 -735.81641092]
 [ -96.47841912 -735.81641089 1034.11298497]]
Are they extremely close?: True
